version: '3'

services:
  backendapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: backend-docker
    container_name: backend-container
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/backend
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
      JWT_SECRET: ${JWT_SECRET}
    # volumes:
    #   - ./:/var/www/backend

  db:
    image: mongo:5
    container_name: mongo-ufounders
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: test
    volumes:
      - ./mongo:/data/db