// Generated by https://quicktype.io

export interface Client {
    _id: string;
    ticket: number;
    present: boolean;
    firstName: string;
    lastName: string;
    birthdate: string;
    email: string;
    phone: string;
    address: string;
}
